version: '3'
services:
  laravel:
    build: ./dockerfiles
    container_name: tester_php
    restart: unless-stopped
    volumes:
      - ".:/var/www"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"     

  nginx:
    image: nginx:latest
    container_name: tester_web
    depends_on:
      - laravel
    volumes:
      - ".:/var/www"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8800:80"
    restart: unless-stopped

  mariadb:
    image: mariadb:10.4
    container_name: tester_mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports: 
      - 8801:3306
    environment:
      MYSQL_DATABASE: datos
      MYSQL_ROOT_PASSWORD: too

  phpmyadmin:
    container_name: tester_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - '8802:80'
    environment:
      PMA_HOST: cure_mysql
      MYSQL_ROOT_PASSWORD: pass

  mongo:
    container_name: tester_mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    container_name: tester_mongo-express
    image: mongo-express:lastest
    restart: unless-stopped
    ports:
      - 8803:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
  
  postgres:
    container_name: tester_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "8804:5432"
    restart: unless-stopped

  pgadmin:
    container_name: tester_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tester@tester.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pass}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8805}:80"
    restart: unless-stopped